### ISSUE TITLE
可以预测训练集里没有出现的喜欢的电影吗？

### ISSUE THREAD

**Issue by yufengjiao** [Holy-Shine/movie_recommend_system#10]
你好，我想请问一下，我看这个项目只能输出训练集里有的电影，那要是给一些测试集电影，可以输出这些电影的rating吗？

**Comment by Holy-Shine** [comment]
> 你好，我想请问一下，我看这个项目只能输出训练集里有的电影，那要是给一些测试集电影，可以输出这些电影的rating吗？

是可以的，只要把测试集的电影整成训练集的格式，然后输入到训练好的网络就能拿到特征向量了
