### ISSUE TITLE
数据集划分问题

### ISSUE THREAD

**Issue by qiyangbo** [Holy-Shine/movie_recommend_system#11]
你好作者，你在训练过程中是否有划分训练集和测试集？

**Comment by Holy-Shine** [comment]
没有划分，只是针对整个数据集的训练，没有做模型评估

**Comment by qiyangbo** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月9日(星期三) 下午3:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Holy-Shine/movie_recommend_system] 数据集划分问题 (Issue #11)





 
没有划分，只是针对整个数据集的训练，没有做模型评估
