### ISSUE TITLE
求博客Markdown源文件

### ISSUE THREAD

**Issue by gzy02** [Holy-Shine/movie_recommend_system#12]
感谢博主开源的推荐系统代码，让我对该领域有了一个初步的认识，深入下去后在[比赛](https://github.com/gzy02/BookRecSys)中取得了良好的成绩。在此冒昧开个issue，求博主2017年的那篇[NCF翻译博客](https://www.cnblogs.com/HolyShine/p/6728999.html)的Markdown源文件，以应付一个课程报告，可以将文件发至邮箱2457256025@qq.com。感激不尽！

**Comment by gzy02** [comment]
Word/LaTeX也行，主要是希望借文章的一些段落添加、修改我的内容，而里面有些格式和公式想直接复用博主写过的

**Comment by Holy-Shine** [comment]
已发送~
