### ISSUE TITLE
能问下为什么data.p里面读出数据是数字吗

### ISSUE THREAD

**Issue by liuguicen** [Holy-Shine/movie_recommend_system#2]
电影名这些好像没看到文本，这个是在哪里转换了吗

**Comment by Holy-Shine** [comment]
数据集里已经全部索引化了。也就是说已经预处理过了。所以电影名是它的所有组成的单词的索引序列，这样做方便后续embedding。
例如，所有电影名组成的词库为`['I','am','roboat','player','one']`，那么电影头号玩家（英文player one）的电影名被索引化为`[3,4]`（下标从0开始）

**Comment by liuguicen** [comment]
哦哦，明白了，谢谢
