### ISSUE TITLE
更新特征保存后的疑问

### ISSUE THREAD

**Issue by CaptainWuDaoKou** [Holy-Shine/movie_recommend_system#3]
楼主你好，训练一个epoch后loss都能收敛到1左右，但每次对相同用户ID电影id输出结构都不一样，而且结果都很奇怪，比如我输入movie_id为1的Toy Story (1995)，推荐的最类似电影是这几个
1588 George of the Jungle (1997)
172 Johnny Mnemonic (1995)
2065 The Purple Rose of Cairo (1985)
1958 Terms of Endearment (1983)
1515 Volcano (1997)
感觉相似度不是很高

**Comment by Holy-Shine** [comment]
是每次训练结果都不一样吗。还是一次训练结果，每次调用KNN都不一样

**Comment by CaptainWuDaoKou** [comment]
运行train model没问题，但是只要重新saveMovieAndUserFeature，结果就变了

**Comment by Holy-Shine** [comment]
我复述一下这个过程，你看是不是这样。
1. train model保存模型参数到本地
2. 加载模型参数（不训练），每次调用savfeature得到的特征结果每次都不一样

**Comment by CaptainWuDaoKou** [comment]
> 我复述一下这个过程，你看是不是这样。
> 
> 1. train model保存模型参数到本地
> 2. 加载模型参数（不训练），每次调用savfeature得到的特征结果每次都不一样

是这样的，推荐的相似用户不会变化，但是相似电影和用户可能喜欢电影都会变，而且相似电影看上去也没很大的关联性

**Comment by Holy-Shine** [comment]
好的，下周我再看看，感谢

**Comment by Holy-Shine** [comment]
@CaptainWuDaoKou 你好，是调用mostlike这个函数每次的结果都不一样吗。照理来说不应该啊

**Comment by CaptainWuDaoKou** [comment]
> @CaptainWuDaoKou 你好，是调用mostlike这个函数每次的结果都不一样吗。照理来说不应该啊

是的，你可以测试一下

**Comment by Holy-Shine** [comment]
@CaptainWuDaoKou 你好，我测试了下。运行两次getUserMostlike，得到的结果一样啊

![image](https://user-images.githubusercontent.com/14997709/71805294-da160c00-30a0-11ea-8aad-fe8109c66580.png)

**Comment by CaptainWuDaoKou** [comment]
> @CaptainWuDaoKou 你好，我测试了下。运行两次getUserMostlike，得到的结果一样啊
> 
> ![image](https://user-images.githubusercontent.com/14997709/71805294-da160c00-30a0-11ea-8aad-fe8109c66580.png)

我运行的结果是重新保存用户和电影特征再进行推荐结果就会不一样
