### ISSUE TITLE
对模型的一些疑问

### ISSUE THREAD

**Issue by Wonz5130** [Holy-Shine/movie_recommend_system#5]
作者你好，首先非常感谢你用 PyTorch 做了移植。不过深度学习小白关于模型方面有点疑问想请教一下。

* 对电影名称是用文本卷积网络进行特征提取的，对其他属性比如用户的 UserID、Gender 和电影的 Genres 等属性是用什么神经网络进行特征提取的？

**Comment by Holy-Shine** [comment]
@Wonz5130 这种categorical变量是用embedding layer做特征抽取。类似于word2vec

**Comment by Wonz5130** [comment]
> @Wonz5130 这种categorical变量是用embedding layer做特征抽取。类似于word2vec

感谢解答。我再理解理解模型，不懂的再来提 issue。
