### ISSUE TITLE
训练集划分问题

### ISSUE THREAD

**Issue by 5663015** [Holy-Shine/movie_recommend_system#7]
楼主您好，我对楼主提供的数据集进行了划分，分成了训练集、验证集和测试集，但训练的时候训练集损失可以降到1以下，验证集的损失却是5左右，我想是不是数据集划分的有问题？划分数据集的代码我参考的这个：https://blog.csdn.net/laugh12321/article/details/99689071

**Comment by Holy-Shine** [comment]
@5663015 我看是这个划分代码是没问题的。是不是验证集太大了。又或者是训练好的模型没保存下来。

**Comment by 5663015** [comment]
> @5663015 我看是这个划分代码是没问题的。是不是验证集太大了。又或者是训练好的模型没保存下来。

谢谢您的回复~我找到问题了，在这行里，https://github.com/Holy-Shine/movie_recommend_system/blob/9b89f770b2df441653b3e7b1001bb99081b521cf/model.py#L67
只用了一个BN，下面有6层共用了这一个BN，我设了6个不同的BN，每层单独用一个，这样验证集的损失就正常了。应该是一个BN无法很好地捕捉所有的特征分布，导致验证集损失异常

**Comment by Holy-Shine** [comment]
@5663015 这么说是好像是有这个问题，我更正下
