### ISSUE TITLE
训练的loss值比较大

### ISSUE THREAD

**Issue by jiusansan222** [Holy-Shine/movie_recommend_system#8]
楼主你好，我是深度学习刚刚入门，尝试了一下模型训练20个epoch，loss值从六千多下降到三千多，但我看到另外一位提问者说1epoch就可以收敛到1，这与我结果相差比较大，请问是什么原因呢？

**Comment by Holy-Shine** [comment]
去掉文本卷积网络试试，那个部分可能有点问题

**Comment by wb014** [comment]
> 去掉文本卷积网络试试，那个部分可能有点问题

你好，我去掉了文本卷积这一部分但loss还是上千，请问问题可能出在哪里

**Comment by yufengjiao** [comment]
我也是一样的问题，但是为什么有人说他的1个epoch可以收敛到1啊？

**Comment by Holy-Shine** [comment]
> 我也是一样的问题，但是为什么有人说他的1个epoch可以收敛到1啊？

麻烦提供下使用的pytorch版本，这个版本太老了，近期打算更新维护下

**Comment by yufengjiao** [comment]
> > 我也是一样的问题，但是为什么有人说他的1个epoch可以收敛到1啊？
> 
> 麻烦提供下使用的pytorch版本，这个版本太老了，近期打算更新维护下

我的pytorch版本是3.7.0

**Comment by Holy-Shine** [comment]
@yufengjiao 刚看了下官网，最新版才1.11.0.....

**Comment by yufengjiao** [comment]
> 

 不好意思我说错了！我的是1.10.1

**Comment by Holy-Shine** [comment]
> > 
> 
> 不好意思我说错了！我的是1.10.1

OK

**Comment by Holy-Shine** [comment]
更新了基于`pytorch:1.9.0`的jupyter，可以参考下，loss实际上是在降的，具体可以看下tensorboard的输出
