### ISSUE TITLE
jupyter循环几次batch就内核中断了

### ISSUE THREAD

**Issue by vijay2907** [Holy-Shine/movie_recommend_system#9]
如题，一次epoch都完不成，循环几次batch就内核中断。各batch的loss已计算并可以打印出来，但后续就莫名其妙中断，也没有任何的错误信息。直接跑.py脚本也是同样的结果，没有任何错误信息，不知道有没有大佬支招。全程cpu利用率不到20%(没用cuda)，内存不到50%就中断了，是配置问题吗？

**Comment by Holy-Shine** [comment]
@vijay2907 你好，这份臭代码写的比较久了，可能没法及时支持。不过按照你的描述，应该是内存不够引起的，你的内存大小是多少

**Comment by vijay2907** [comment]
> @vijay2907 你好，这份臭代码写的比较久了，可能没法及时支持。不过按照你的描述，应该是内存不够引起的，你的内存大小是多少

没关系，我也是学习一下。内存是16G的，batch_size我试过调成1也是循环多几次就中断了。stackoverflow见过相关问题但似乎没有解决，而且也比较久了。
[https://stackoverflow.com/questions/56759112/how-to-fix-the-kernel-appears-to-have-died-it-will-restart-automatically-caus](url)

**Comment by Holy-Shine** [comment]
@vijay2907 IDE运行的话中断的时候有报错吗

**Comment by vijay2907** [comment]
@Holy-Shine 没试过pycharm这种IDE运行，用vscode/jupyter/cmd直接运行结果都是一样，循环几次就结束了，没有报错。因为我代码print了loss和batch_idx，就是打印几次就结束了。

**Comment by Holy-Shine** [comment]
@vijay2907 那有点奇怪的，能打几个batch的话证明内存上应该没啥问题的，数据也是动态分批读取的，等我有时间了再回顾下代码，，最近太忙了抱歉

**Comment by vijay2907** [comment]
@Holy-Shine 没关系，谢谢。
